---
title             : "EDLD651 Final Project"
shorttitle        : "Title"

author: 
  - name          : "Maggie Head"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Writing - Original Draft Preparation
      - Writing - Review & Editing
  - name          : "Sarah Spafford"
    affiliation   : "1"
    role:
      - Writing - Review & Editing
  - name          : "Heather Terral"
    affiliation   : "1"
    role:
      - Writing - Review & Editing
affiliation:
  - id            : "1"
    institution   : "University of Oregon"

authornote: |
  This will be an author note.

  Enter author note here.

abstract: |
  This will be an abstract.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output:
  papaja::apa6_pdf:
    citation_package: biblatex
---

```{r libraries}
library(papaja)
r_refs("r-references.bib")
library(haven)
library(janitor)
library(tidyverse)
library(apaTables)
library(rio)
library(qwraps2)
library(lm.beta)
library(ggiraphExtra)
library(psych)
library(lavaan)
library(lavaanPlot)
```

```{r setup}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                     eval=TRUE
                     )
```

```{r data import, include = FALSE}
stride <- read_sav("data/project_stride_data.sav") %>% 
  as_tibble() %>% 
  janitor::clean_names() 
head(stride)

#CODEREVIEW_df: This is a nice way to pull in data, tidy it, and pick out the specific data that you want. Nice work! I 
# had wondered about condensing a bit with the as.numeric and as.factor code lines; though, after a bit of trial and error
# I didn't get very far in condensing. Overall, nice job!
stridy <- stride %>%
  drop_na(perwellb_2, dis_d_total, chr_gen_2, connect) %>% 
  filter(sexori <= 6) %>% 
  select(sexori,
       age,
       ethnic,
       gender,
       chr_gen_2,
       perwellb_2,
       dis_d_total,
       connect)
stridy$perwell_b2 <- as.numeric(stridy$perwellb_2)
stridy$chr_gen_2 <- as.numeric(stridy$chr_gen_2)
stridy$sexori <- as.factor(stridy$sexori)
stridy$gender <- as.factor(stridy$gender)
stridy$ethnic <- as.factor(stridy$ethnic)
head(stridy)




```

```{r tidy data, include = FALSE}

#stridy %>%
#  mutate(ethnic = recode(ethnic,
      #   `Black/African-American,` = "Black/African American",
        # `White,` = "White"))

stridy_wide <-stridy %>%
  group_by(sexori, ethnic) %>%
  characterize() %>%
  summarize(mean_connect = mean(connect)) %>%
  pivot_wider(
    names_from = ethnic,
    values_from = mean_connect
  )

stridy_long <- stridy_wide %>%
  pivot_longer(cols = c(2:4),
               names_to = "Ethnicity",
               values_to = "Connectedness")
               

#CODEREVIEW_df: this is both a clever and necessary chunk for the final assignment. I like how you pivoted long, then wide
# to break data down by ethnicity!

```

```{r mean plot, results="asis"}
#CODEREVIEW_df: I found this code chunk to be quite elegant in piping your stridy data to a grouped subsample of the dataset
# and then using labs() to make an aesthetically pleasing figure. One idea - have you considered adding error bars? I think
# it adds a bit of value to the reader understanding the variance around central tendency data. I provided a couple of lines
# of code to show what I'm thinking.

sexori <- stridy %>% 
  mutate(sexori = as.factor(sexori))

mean_plot <- stridy %>% 
  group_by(sexori) %>% 
  characterize() %>% 
  summarize(mean_disc = mean(dis_d_total)) %>% 
  ggplot(aes(sexori, mean_disc)) +
  geom_col(fill = "plum4", alpha = .75) +
  #this next line of code adds a 1SD error bar on either side of the averages per sexual orientation. In my mind, it adds a 
  #bit of confidence that means are meaningfully different (e.g., Queer vs. Other - LGB)
  geom_errorbar(aes(ymin = mean_disc-sd(mean_disc), ymax = mean_disc+sd(mean_disc), width = 0.2)) +
  
  labs(title = "Experiences of Everyday Discrimination",
       subtitle = "According to Sexual Orientation") +
  xlab("Sexual Orientation") +
  ylab("Average Discriminatory Experiences")
plot(mean_plot)

```



```{r summary table, results= "asis"}

#CODEREVIEW_df: Really interesting code here; I hadn't seen the syntax "= ~" before quite like how it's setup here. Nice!
options(qwraps2_markup = "markdown")
summary1 <-
  list("Everyday Discrmination" =
         list("min"       = ~ round(min(dis_d_total, na.rm = TRUE),2),
              "median"    = ~ round(median(dis_d_total, na.rm = TRUE),2),
              "max"       = ~ round(max(dis_d_total, na.rm = TRUE),2),
              "mean (sd)" = ~ qwraps2::mean_sd(dis_d_total, na_rm = TRUE)),
       "Chronic Strain" =
         list("min"       = ~ round(min(chr_gen_2, na.rm = TRUE),2),
              "median"    = ~ round(median(chr_gen_2, na.rm = TRUE),2),
              "max"       = ~ round(max(chr_gen_2, na.rm = TRUE),2),
              "mean (sd)" = ~ qwraps2::mean_sd(chr_gen_2, na_rm = TRUE)),
       "Psychological Wellbeing" =
         list("min"       = ~ round(min(perwellb_2, na.rm = TRUE),2),
              "median"    = ~ round(median(perwellb_2, na.rm = TRUE),2),
              "max"       = ~ round(max(perwellb_2, na.rm = TRUE),2),
              "mean (sd)" = ~ qwraps2::mean_sd(perwellb_2, na_rm = TRUE)),
       "Social Connectedness" =
         list("min"       = ~ round(min(connect, na.rm = TRUE),2),
              "median"    = ~ round(median(connect, na.rm = TRUE),2),
              "max"       = ~ round(max(connect, na.rm = TRUE),2),
              "mean (sd)" = ~ qwraps2::mean_sd(connect, na_rm = TRUE))
  )
table_total <- summary_table(stridy, summary1)
table_total

#CODEREVIEW_df: another learning point - hadn't seen something quite like mutate_at() with characterizing. It leads to a well constructed table!
grouped_table <- summary_table(stridy%>%
                                 mutate_at('sexori', characterize),
                               summaries = summary1, by = c("sexori"))
grouped_table
```

# Introduction
# Methods


## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results  
``` {r regression}

#CODEREVIEW_df: this is a really useful example of plotting a regression. Hadn't seen ggPredict before - neat!
mod <- lm(perwellb_2 ~  1 + dis_d_total + chr_gen_2 + connect, data = stridy)
summary(lm.beta(mod))

ggplot(stridy, aes(x = perwellb_2, y = dis_d_total)) +
   geom_point(color = "orange") +
   geom_smooth(method = "lm") +
   theme_minimal()
```
```{r correlation panels}

#CODEREVIEW_df: Also an elegant little section of code to plot some visualizations. It is a little difficult for me to track what exactly I'm looking at here; though, this will almost certainly come with your explanation when you put together your final project. Clearly, your code is there and I'm really interested to know more about the figure(s) that I'm looking at!
pairs.panels(stridy[,-c(1:4, 9)], 
             method = "pearson", 
             hist.col = "darkmagenta",
             density = FALSE,
             ellipses = FALSE,
             lm = TRUE, 
             labels 
             )

```
```{r lavaan plot}

model <- 'perwellb_2 ~ dis_d_total + chr_gen_2 + connect'

fit <- sem(model, data = stridy)
summary(fit)

labels <- list(perwellb_2 = "Psychological Wellbeing", dis_d_total = "Discrimination", chr_gen_2 = "Chronic Strain", connect = "Social Connectedness")

lavaanPlot(model = fit, labels = labels, node_options = list(shape = "box", fontname = "Garamond"), edge_options = list(color = "black"), coefs = T, stars = c("regress"))
```

# Discussion


\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
